[static_error_patterns]
# Import Errors
import_error = {
    pattern = "ModuleNotFoundError|ImportError",
    severity = "high",
    category = "import",
    fix_strategy = "import_resolution"
}

# Syntax Errors
syntax_error = {
    pattern = "SyntaxError|IndentationError",
    severity = "critical",
    category = "syntax",
    fix_strategy = "syntax_correction"
}

# Type Errors
type_error = {
    pattern = "TypeError|AttributeError",
    severity = "high",
    category = "type",
    fix_strategy = "type_resolution"
}

# Name Errors
name_error = {
    pattern = "NameError|UnboundLocalError",
    severity = "medium",
    category = "scope",
    fix_strategy = "scope_resolution"
}
