# LangGraph Configuration for Navigator Agent

<<<<<<< HEAD
[navigator_agent]
# Maximum number of iterations for workflow
max_iterations = 3

# Timeout for workflow execution (in seconds)
timeout = 300  # 5 minutes

# Logging configuration
logging_level = "INFO"

# Subagent configuration
[navigator_agent.subagents]
reflection_depth = 2
solution_generation_attempts = 3
error_analysis_threshold = 0.7

# Model configuration
[navigator_agent.model]
provider = "openai"
model_name = "gpt-4-turbo"
temperature = 0.7
max_tokens = 4096

# Workflow routing configuration
[navigator_agent.routing]
max_solutions_for_selection = 5
min_solution_quality_threshold = 0.8
error_escalation_threshold = 0.6
=======
[workflow]
max_iterations = 5
timeout_seconds = 60
default_temperature = 0.3
retry_attempts = 3

[subagents]
reflection_weight = 0.4
solution_weight = 0.3
analysis_weight = 0.3
>>>>>>> 62d5686fe3b4abbb8197ec527d7129df0198e919

[performance]
max_concurrent_sessions = 50
max_tokens = 4096
context_window_size = 32000
response_time_threshold_ms = 2000

[security]
api_key_encryption = "AES-256"
token_chunk_size = 8192
summary_compression_ratio = 0.5
input_sanitization = true
max_retry_attempts = 3

[logging]
level = "INFO"
trace_enabled = true
audit_trail = true

[llm]
provider = "openai"
model = "gpt-4-turbo"

[error_handling]
retry_strategy = "exponential_backoff"
max_error_threshold = 2
