# Solution Selection Configuration

[selection_criteria]
# Minimum technical depth required for a solution to be considered
min_technical_depth = 0.7

# Minimum implementation readiness score
min_implementation_readiness = 0.8

# Maximum number of solutions to consider for selection
max_solutions_for_selection = 5

[performance]
# Maximum time allowed for solution selection (in milliseconds)
max_selection_time = 500

[evaluation_weights]
# Weights for different evaluation metrics
technical_comprehensiveness = 0.3
scalability = 0.2
innovation = 0.2
practical_implementability = 0.2
alignment_with_problem_statement = 0.1

[fallback_strategy]
# Strategy to use if no solution meets the minimum criteria
# Options: "regenerate", "select_best_available", "halt"
fallback_action = "regenerate"
