---
# Static Analysis Configuration

# Severity Levels
severity_levels:
  low: 1
  medium: 2
  high: 3
  critical: 4

# Error Pattern Matching Rules
error_patterns:
  syntax_errors:
    - pattern: "IndentationError"
      severity: high
      fix_strategy: auto_indent
    
    - pattern: "SyntaxError"
      severity: critical
      fix_strategy: syntax_correction

  type_hints:
    - pattern: "Type mismatch"
      severity: medium
      fix_strategy: type_annotation_fix

  naming_conventions:
    - pattern: "snake_case_violation"
      severity: low
      fix_strategy: rename_to_snake_case

  import_management:
    - pattern: "Unused import"
      severity: low
      fix_strategy: remove_unused_import

# Language-Specific Configurations
python_specific:
  pep8_checks:
    - max_line_length: 120
    - indent_size: 4
    - docstring_requirements:
        min_length: 10
        required_sections: 
          - description
          - parameters
          - returns
