[tool.poetry]
name = "sprint-navigator-agent"
version = "0.1.0"
description = "AI-powered Navigator Agent system using LangChain and LangGraph"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.1.21"
langgraph = "^0.1.2"
openai = "^1.0.0"
pydantic = "^2.0.0"
toml = "^0.10.2"
tiktoken = "^0.5.2"
faiss-cpu = "^1.7.4"
langchain-community = "^0.0.20"
uuid = "^1.30"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
mypy = "^1.3.0"
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
pytest-mock = "^3.12.0"
pytest-asyncio = "^0.23.2"

[tool.poetry.scripts]
navigator-agent = "src.navigator_agent.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 100
