[tool.poetry]
name = "sprint-py"
version = "0.1.0"
description = "Python script to plan and modify code"
authors = ["Bhavesh Ramburn <nitrogen@gmail.com>"]
license = "Copyright 2025"
readme = "README.md"

[tool.poetry.scripts]
test = "pytest"
sprint = "cli_interface:cli"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
langchain-community = "^0.3.14"
faiss-cpu = "^1.9.0.post1"
openai = "^1.59.7"
langchain = "^0.3.14"
pytest = "^8.3.4"
pathspec = "^0.12.1"
chardet = "^5.2.0"
python-dotenv = "^1.0.1"
tiktoken = "^0.8.0"
sentence-transformers = "^3.3.1"
numpy = "^2.2.1"
langchain-openai = "^0.3.0"
pyarrow = "^19.0.0"
typing-extensions = "^4.12.2"
scikit-learn = "^1.6.1"
scipy = "^1.15.1"
pandas = "^2.2.3"
subprocess32 = "^3.5.4"
langgraph = "^0.2.64"
pydantic = "^2.10.5"
langchain-core = "^0.3.30"
aiofiles = "^24.1.0"
click = "^8.1.7"
spacy = ">=3.8.4,<3.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
mypy = "^1.10.0"
pytest-asyncio = "^0.23.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
