from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional

class CodeStructure(BaseModel):
    """Model for representing the structure of generated code"""
    classes: List[Dict[str, Any]] = Field(default_factory=list, description="List of classes defined in the code")
    functions: List[Dict[str, Any]] = Field(default_factory=list, description="List of functions defined in the code")
    imports: List[str] = Field(default_factory=list, description="List of imports in the code")
    variables: List[Dict[str, Any]] = Field(default_factory=list, description="List of variables in the code")

class PlanInfo(BaseModel):
    """Model for storing analyzed plan information"""
    function_name: str = Field(description="Name of the function to implement")
    parameters: List[str] = Field(default_factory=list, description="List of function parameters")
    description: str = Field(description="Description of the plan")

class StaticAnalysisResult(BaseModel):
    """Model for storing static analysis results"""
    syntax_errors: List[Dict[str, Any]] = Field(default_factory=list, description="List of syntax errors found")
    style_warnings: List[Dict[str, Any]] = Field(default_factory=list, description="List of style warnings")
    complexity_score: float = Field(default=1.0, description="Code complexity score")

class TestResult(BaseModel):
    """Model for storing test results"""
    type: str = Field(description="Type of test (e.g., 'static_analysis', 'unit_tests')")
    passed_tests: int = Field(description="Number of tests passed")
    total_tests: int = Field(description="Total number of tests")
    results: Dict[str, Any] = Field(description="Detailed test results data")

class DriverState(BaseModel):
    """Model for managing driver state with structured output"""
    plan: Dict[str, Any] = Field(description="The implementation plan")
    generated_code: Optional[str] = Field(default=None, description="The code generated by the model")
    code_structure: Optional[CodeStructure] = Field(default=None, description="Structured representation of the generated code")
    test_results: List[TestResult] = Field(default_factory=list, description="List of test results")
    memory: Dict[str, Any] = Field(default_factory=dict, description="Memory dictionary for saving and managing state")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    next_node: Optional[str] = Field(default=None, description="Next node to execute")
    refined_code: Optional[str] = Field(default=None, description="Refined version of the code")